### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by bondzula** [lifepillar/vim-cheat40#2]
Hi, amazing plugin, looks and works relay nice but i was wondering could you make it smarter? What i mean by this is, if i start insert mode, i wanna see only insert mode shortcuts, because most of the time i wont even notice I'm not using some useful shortcut. Whats more, something like a "tips and tricks' group where commands like 'Ctrl-o -> puts you in normal mode for only one command' could be placed as it doesn't relay belong in some distinct category but is useful nonetheless. This way it would be much more useful for vim noobs like myself. Second improvement could be file type detection, if I'm in a python file, display python snippets or something, but for this i would make another shortcut not to lose vim cheat sheet.
Now, I'm not asking for this, its only a suggestion, i would implement this myself if i knew how :D, but i still wanna be of some help in case you decide to do this.

For insert mode i know there is event InsertEnter, and InsertLeave, maybe that could be helpful (i have no idea :D)

And for file type detection i saw this discussion https://stackoverflow.com/questions/5194994/vim-script-buffer-cheatsheet-toggle

**Comment by lifepillar** [comment]
Those are all nice ideas, but they would probably fit a different plugin: Cheat40 was born to be just a simple (if not simplistic) static cheat sheet, and it would take quite some work to implement some dynamic behaviour that makes sense. I certainly have no time (or interest, to be honest) to do it—pull requests are always welcome, though.

Anyway, along the lines of what you are suggesting there are already more sophisticated plugins. You may take a look at [vim-leader-guide](https://github.com/hecal3/vim-leader-guide), for example.

**Comment by bondzula** [comment]
I didn't know about vim-leader-guide, i will definitely check that out, thanks for suggestion, and to tell you the truth over past few days i grow to like Cheat40 non invasive way of reminding me of what i want to know. You may close the issue now, thanks for your time
