### ISSUE TITLE
install using vim-plug

### ISSUE THREAD

**Issue by kyp0717** [lifepillar/vim-cheat40#5]
Can you provide instruction on how to install using vim-plug?
Thanks

**Comment by lifepillar** [comment]
I am not using vim-plug, but I *think* that this line in your `vimrc` should do it:

```vim
Plug 'lifepillar/vim-cheat40'
```

**Comment by kyp0717** [comment]
Thanks.  That works!  Actually, that was what I did but it did not work the first time for some reason.  May need to wait a little bit.
