### ISSUE TITLE
Set the Menus (ie Files, Windows) to folded state

### ISSUE THREAD

**Issue by kyp0717** [lifepillar/vim-cheat40#6]
Hi.
I have been starting to use your vim plugin.  It is very helpful thank you.
Right now, when you open the cheatsheet, all the menus are fully expanded.  Is there a way to make the menus folded?

Thanks,
Ky

**Comment by lifepillar** [comment]
Currently, there is no option to change the foldlevel, but I may add one.

In the meantime, you may solve your issue by creating a file inside your `.vim` folder (`$HOME/.vim/after/ftplugin/cheat40.vim`) with this content:

```vim
setlocal foldlevel=0
```

**Comment by lifepillar** [comment]
I have added a new option to set the fold level. So, the workaround above is not needed any longer. Just add this to your `vimrc`:

```vim
let g:cheat40_foldlevel = 0
```
