### ISSUE TITLE
Plugin-specific cheat sheets

### ISSUE THREAD

**Issue by hupfdule** [lifepillar/vim-cheat40#7]
Hello,

is it possible to have plugin-specific cheat sheets?

What I am thinking of is having a sheet for e.g. a markdown plugin that is only displayed while a markdown buffer is being edited.

**Comment by lifepillar** [comment]
Not really. But if a plugin contains a `cheat40.txt` file, it will be added to the global cheat sheet.

This might be a good addition, but I can't promise I'll be able to implement it any time soon. Pull requests are welcome, though!
